// All user-facing text lives here (English only for now), so translations can be added later.
export const copy = {
  landing: {
    nav: { how: 'How it works', cards: 'Cards', pricing: 'Pricing', cta: 'Get started' },
    hero: {
      line1: 'Your menu, one tap',
      accent: 'away',
      body: 'Customers tap the card. Your menu opens on their phone. No app.',
      cta: 'Get your card',
      secondary: 'How it works',
      phoneLabel: 'Sample menu on a phone',
    },
    how: {
      title: 'Three steps,',
      accent: 'zero apps.',
      steps: [
        { title: 'Tap', body: 'Phone touches the card.' },
        { title: 'Browse', body: 'Your menu opens instantly.' },
        { title: 'Update', body: 'Edit prices and items anytime.' },
      ],
    },
    cards: { title: 'One tap. Any link.', body: 'Menu, socials, reviews, website.' },
    pricing: {
      title: 'Simple pricing',
      badge: 'Custom package',
      name: 'NFC + Website package',
      from: 'Starting at',
      body: 'Perfect for cafés, restaurants & stores.',
      features: [
        'Free setup & guide',
        'Custom website with menu: add, edit, delete items',
        'Free hosting + domain included',
        'Customers browse the menu on their phone',
      ],
      cta: 'Get started',
      bundles: {
        title: 'Turn every customer into a review',
        body: 'Simple tap. More follows, reviews & visibility.',
        best: 'Best value',
        save: 'Save',
        getNow: 'Get now',
        items: {
          one: {
            name: '1 NFC card',
            perks: ['Free setup & guide', 'Choose 1: Facebook, Instagram or Google review'],
          },
          two: {
            name: 'Any 2 cards',
            perks: ['Free setup & guide', 'Choose any 2: Facebook, Instagram or Google review'],
          },
          three: {
            name: 'All 3 cards',
            perks: ['Free setup & guide', 'Facebook + Instagram + Google review'],
          },
        },
      },
    },
    footer: 'All rights reserved.',
  },
  order: {
    title: 'Get your NFC card',
    close: 'Close',
    cardsLegend: { one: 'Choose 1 card', two: 'Choose any 2 cards', three: 'Your 3 cards' },
    cardNames: { facebook: 'Facebook', instagram: 'Instagram', google: 'Google review' },
    deliveryTitle: 'Delivery details',
    fields: {
      fullName: { label: 'Full name', placeholder: 'Juan Dela Cruz' },
      phone: {
        label: 'Mobile number',
        placeholder: '0917 123 4567',
        hint: 'We call or text this number to confirm your order.',
      },
      province: { label: 'Province', placeholder: 'Start typing' },
      city: { label: 'City / municipality', placeholder: 'Cebu City' },
      barangay: { label: 'Barangay', placeholder: 'Lahug' },
      street: { label: 'Street, house or building no.', placeholder: '12 Salinas Drive' },
      landmark: {
        label: 'Landmark and exact location',
        placeholder: 'Blue gate beside the 7-Eleven, 2nd house',
        hint: 'Gate color, nearby store, floor or unit. Helps us find you.',
      },
    },
    consent: 'I agree that NFC Menu uses these details only to deliver and set up my order.',
    submit: 'Place order',
    sending: 'Sending',
    errors: {
      required: 'This is required.',
      tooShort: 'This is too short.',
      tooLong: 'This is too long.',
      invalid: 'Remove special characters.',
      phone: 'Enter a PH mobile number, like 0917 123 4567.',
      fullName: 'Use letters, spaces and . - only.',
      choose: 'Choose your card.',
      wrongCount: 'Choose exactly the number of cards in your bundle.',
      consent: 'Please agree to continue.',
      summary: 'Please fix the highlighted fields.',
      submit: {
        network: 'Could not reach the server. Check your connection and try again.',
        rateLimited: 'Too many tries. Please wait a few minutes.',
        rejected: 'We could not accept this order. Please check your details.',
      },
    },
    success: {
      title: 'Order received',
      body: 'We will contact you at {phone} to confirm your order and free setup.',
      reference: 'Reference',
      demo: 'Demo mode: no server is connected yet, so nothing was sent.',
      done: 'Done',
    },
  },
  menu: {
    comingSoon: 'Menu coming soon.',
  },
  dashboard: { title: 'Dashboard' },
  admin: { title: 'Admin' },
  notFound: {
    title: 'Page not found',
    body: 'The link may be wrong or the menu may have moved.',
    home: 'Go home',
  },
  error: {
    title: 'Something went wrong',
    body: 'Please try again in a moment.',
    retry: 'Reload',
  },
} as const
